python train_varnet.py \
  -b 1 \
  -e 40 \
  -l 1e-4 \
  -r 100 \
  -n 'test_Varnet2' \
  -t '/root/Data/train/' \
  -v '/root/Data/val/' \
  --cascade 6 \
  --chans 13 \
  --sens_chans 8 \
  --seed 146 \
  --use-weighted-loss \
  --aug_on \
  --aug_delay 4 \
  --aug_strength 0.5 \
  --aug_max_rotation 180.0 \
  --aug_max_shearing_x 15.0 \
  --aug_max_shearing_y 5.0 \
  --gradient-checkpoint